import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LayoutProp } from "@/types/common";
import HeaderMain from "@/modules/common/HeaderMain";
import ReactQueryClient from "@/components/common/ReactQueryProvider";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProp) {
  return (
    <html lang="en" className="antialiased">
      <ReactQueryClient>
        <body
          className={`${geistSans.variable} ${geistMono.variable} my-5 bg-amber-50`}
        >
          <div className="min-w-[900px] max-w-[1200px] mx-auto">
            <HeaderMain />
            {children}
          </div>
          <Toaster richColors position="bottom-center" />
        </body>
      </ReactQueryClient>
    </html>
  );
}
